ignoredBuiltDependencies:
  - '@vercel/speed-insights'
  - canvas
  - contentlayer
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - contentlayer2
  - rome
